version: '3'

volumes:
  node_modules:
services:
  itrackflow-dev:
    build:
      context: .
      dockerfile: ./Dockerfile.dev
    ports:
      - '3000:3000'
      - '24678:24678'
    volumes:
      - .:/src
      - node_modules:/src/node_modules
  itrackflow-dev-db:
    image: mongo:latest
    container_name: itrackflow-dev-db
    ports:
      - 27017:27017
    volumes:
      - ./mongo:/data/db
