export default {
	refreshPlayerKey: 0,
	audioSrc: '',
	audioElement: null,
	isPlaying: false,
	isPaused: false,
	audioDuration: 0,
	audioCurrentTime: 0,
	setAudioSrc: vi.fn(),
	setAudioElement: vi.fn(),
	setAudioCurrentTime: vi.fn(),
	play: vi.fn(),
	pause: vi.fn(),
	stop: vi.fn(),
};
